---
name: test

on:
  push:
    branches: release
  pull_request:
    branches: release
    types: [opened, reopened, edited]
  schedule:
    - cron: "0 13 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_branch: [emacs-28, master]

    steps:
      - uses: actions/checkout@v2
      - name: Run test suite
        run: make docker EMACS_BRANCH="${{ matrix.emacs_branch }}" DOCKER_FLAGS='' DOCKER_COMMAND='make test'
